// <auto-generated />
using System;
using CCMS.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCMS.DAL.Migrations
{
    [DbContext(typeof(CcmsDbContext))]
    [Migration("20250815215827_EditScanLabDoctorId")]
    partial class EditScanLabDoctorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiomedicalEngineerMedicalDevice", b =>
                {
                    b.Property<int>("BiomedicalEngineersUID")
                        .HasColumnType("int");

                    b.Property<string>("MedicalDevicesSerialNumber")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BiomedicalEngineersUID", "MedicalDevicesSerialNumber");

                    b.HasIndex("MedicalDevicesSerialNumber");

                    b.ToTable("BiomedicalEngineerMedicalDevice", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Address", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.HasKey("PersonId", "address");

                    b.ToTable("Person_Address", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("RNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RNumber");

                    b.ToTable("Book", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Department", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("Id");

                    b.ToTable("FamilyMember", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.MedicalDevice", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExpirationHours")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MDName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MDStatus")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("rNumber")
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("rNumber");

                    b.ToTable("MedicalDevice", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.MedicalDevice_Room", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("RNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("RNumber");

                    b.ToTable("MedicalDevice_Room", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAcceptable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalHistory", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.PatientFamily", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PatientId", "FamilyMemberId");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("Patient_FamilyMember", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Person", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UID"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MidName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("PType")
                        .HasColumnType("int");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("UID");

                    b.ToTable("Person", "ccms");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.HasKey("PersonId", "Number");

                    b.ToTable("Person_PhoneNumber", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Room", b =>
                {
                    b.Property<string>("RNumber")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int>("rstatus")
                        .HasColumnType("int");

                    b.Property<int>("rtype")
                        .HasColumnType("int");

                    b.HasKey("RNumber");

                    b.HasIndex("DeptId");

                    b.ToTable("Room", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LDID")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScanTech")
                        .HasColumnType("int");

                    b.Property<int>("ScanType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LDID");

                    b.HasIndex("PatientId");

                    b.ToTable("Scan", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.WorkingSlot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("endTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("startTime")
                        .HasColumnType("time");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("WorkingSlot", "ccms");
                });

            modelBuilder.Entity("EmployeeWorkingSlot", b =>
                {
                    b.Property<int>("EmployeesUID")
                        .HasColumnType("int");

                    b.Property<int>("WorkingSlotsid")
                        .HasColumnType("int");

                    b.HasKey("EmployeesUID", "WorkingSlotsid");

                    b.HasIndex("WorkingSlotsid");

                    b.ToTable("EmployeeWorkingSlot", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Employee", b =>
                {
                    b.HasBaseType("CCMS.DAL.Entities.Person");

                    b.Property<int?>("AdmId")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("EType")
                        .HasColumnType("int");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MgrId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasIndex("AdmId");

                    b.HasIndex("DeptId");

                    b.HasIndex("MgrId");

                    b.ToTable("Employee", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Patient", b =>
                {
                    b.HasBaseType("CCMS.DAL.Entities.Person");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.ToTable("Patient", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.BiomedicalEngineer", b =>
                {
                    b.HasBaseType("CCMS.DAL.Entities.Employee");

                    b.ToTable("BiomedicalEngineer", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Doctor", b =>
                {
                    b.HasBaseType("CCMS.DAL.Entities.Employee");

                    b.Property<int>("major")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.ToTable("Doctor", "ccms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.LabDoctor", b =>
                {
                    b.HasBaseType("CCMS.DAL.Entities.Employee");

                    b.ToTable("LabDoctor", "ccms");
                });

            modelBuilder.Entity("BiomedicalEngineerMedicalDevice", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.BiomedicalEngineer", null)
                        .WithMany()
                        .HasForeignKey("BiomedicalEngineersUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.MedicalDevice", null)
                        .WithMany()
                        .HasForeignKey("MedicalDevicesSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Address", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Book", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Doctor", "Doctor")
                        .WithMany("Books")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.Patient", "Patient")
                        .WithMany("Books")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.Room", "Room")
                        .WithMany("Books")
                        .HasForeignKey("RNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.MedicalDevice", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Room", "Room")
                        .WithMany("MedicalDevices")
                        .HasForeignKey("rNumber");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.MedicalDevice_Room", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.MedicalDevice", "MedicalDevice")
                        .WithMany()
                        .HasForeignKey("SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalDevice");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.MedicalHistory", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Patient", "Patient")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.PatientFamily", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.FamilyMember", "FamilyMember")
                        .WithMany("PatientFamilyMembers")
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.Patient", "Patient")
                        .WithMany("PatientFamilyMembers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyMember");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.PhoneNumber", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Person", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Room", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Scan", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.LabDoctor", "LabDoctor")
                        .WithMany("Scans")
                        .HasForeignKey("LDID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.Patient", "Patient")
                        .WithMany("Scans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabDoctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("EmployeeWorkingSlot", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMS.DAL.Entities.WorkingSlot", null)
                        .WithMany()
                        .HasForeignKey("WorkingSlotsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Employee", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Employee", "Admin")
                        .WithMany()
                        .HasForeignKey("AdmId");

                    b.HasOne("CCMS.DAL.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId");

                    b.HasOne("CCMS.DAL.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("MgrId");

                    b.HasOne("CCMS.DAL.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("CCMS.DAL.Entities.Employee", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Patient", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("CCMS.DAL.Entities.Patient", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.BiomedicalEngineer", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("CCMS.DAL.Entities.BiomedicalEngineer", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Doctor", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("CCMS.DAL.Entities.Doctor", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.LabDoctor", b =>
                {
                    b.HasOne("CCMS.DAL.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("CCMS.DAL.Entities.LabDoctor", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.FamilyMember", b =>
                {
                    b.Navigation("PatientFamilyMembers");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Room", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("MedicalDevices");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Patient", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("MedicalHistories");

                    b.Navigation("PatientFamilyMembers");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.Doctor", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CCMS.DAL.Entities.LabDoctor", b =>
                {
                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
